apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /hello-world(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: hello-world-svc
            port:
              name: http
