apiVersion: v1
kind: Service
metadata:
  name: esphome-svc
spec:
  selector:
    app: esphome
  ports:
    - protocol: TCP
      name: esphome
      port: 6052
      targetPort: 6052
      nodePort: 30082
  type: NodePort

